#!/usr/bin/env bash

gap_between=40

path=$(dirname $(realpath $0))

get_var() {
    var_name=$1
    echo "$line" | sed "s/.*$var_name=\[\([^]]*\)\].*/\1/g"
}

active_notifications() {
    processes=$(ps aux | awk '/conky/ && !/awk/ {print $2}' | wc -l)
    echo $(expr "$processes" + 1)
}

get_y_gap() {
    echo $(expr "$gap_between" \* $(expr "$(active_notifications)" \* 3) - $gap_between)
}

tail -n 0 -f /var/log/notification-center.log |
    while read -r line; do
        the_source=$(get_var "source")
        summary=$(get_var "summary")
        body=$(get_var "body")
        timeout=$(get_var "timeout")

        if [ -z "$timeout" ]; then
            timeout="8000"
        fi

        if [[ "$timeout" == "-1" ]]; then
            timeout="8000"
        fi

        Y_GAP=$(get_y_gap) heading="$summary" message="$body" program="$the_source" conky -c $path/../ui/notification.lua &
        play "$path/../notify-sound.wav"
        process_id=$(sleep 1; ps aux | awk '/conky/ && !/awk/ {print $2}' | tail -1)
        sleep_amount=$(expr $(expr "$timeout" / 1000) % 60)
        (sleep "$sleep_amount"; kill "$process_id") &
    done
