#!/usr/bin/env bash

gap_between=40

path=$(dirname $(realpath $0))

get_var() {
    local var_name=$1
    echo "$line" | sed "s/.*$var_name=\[\([^]]*\)\].*/\1/g"
}

active_notifications() {
    local processes=$(ps aux | awk '/conky/ && !/awk/ {print $2}' | wc -l)
    echo $(expr "$processes" + 1)
}

get_y_gap() {
    echo $(expr "$gap_between" \* $(expr "$(active_notifications)" \* 3) - $gap_between)
}

get_timeout_from_var() {
    local timeout=$(get_var "timeout")

    if [ -z "$timeout" ]; then
        timeout="8000"
    fi

    if [[ "$timeout" == "-1" ]]; then
        timeout="8000"
    fi
    echo "$timeout"
}

get_timeout_no_var() {
    echo "8000"
}

main() {
    tail -n 0 -f /var/log/notification-center.log |
        while read -r line; do
            local the_source=$(get_var "source")
            local summary=$(get_var "summary")
            local body=$(get_var "body")
            local timeout=$(get_timeout_no_var)

            Y_GAP=$(get_y_gap) heading="$summary" message="$body" program="$the_source" conky -c $path/../ui/notification.lua &
            play "$path/../notify-sound.wav"
            local process_id=$(sleep 1; ps aux | awk '/conky/ && !/awk/ {print $2}' | tail -1)
            local sleep_amount=$(expr $(expr "$timeout" / 1000) % 60)
            (sleep "$sleep_amount"; kill "$process_id") &
        done
}

main
